[build]
  command = "npm install --no-audit --no-fund && rm -rf .netlify && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.0"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
