[build]
  command = "npm ci --force && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
